# .golangci.yaml — v2
version: "2"

run:
  timeout: 20m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    #- depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    #- err113
    - errname
    - errorlint
    - exhaustive
    #- forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    #- goconst
    #- gocritic
    - gocyclo
    #- godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - govet
    - importas
    - interfacebloat
    - ineffassign
    - lll
    - loggercheck        # was logrlint
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    #- nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    #- paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    #- revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testpackage
    #- thelper
    #- tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - unused
    - wastedassign
    - whitespace
    #- wsl_v5 # was wsl
    - copyloopvar        # replaces exportloopref

# v2 treats formatters separately (gofmt/gofumpt/goimports/gci)
formatters:
  enable:
    - gci
    - goimports
    - gofumpt
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/screwyprof)
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/screwyprof
    gofmt:
      simplify: false

issues:
  new-from-rev: master
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gosec
        - dupl
        - err113
    - path: test_helpers\.go
      linters:
        - funlen
        - gosec
        - dupl
        - err113
    - path: testdsl
      linters:
        - wrapcheck

output:
  sort-order:
    - linter
    - file
